# Generated by Django 4.2.28 on 2026-07-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status_reason',
            field=models.TextField(blank=True),
        ),
    ]
