import { Link } from "react-router-dom";
import { LegalPage } from "../components/LegalPage";
import { useSeo } from "../lib/seo";

export function PrivacyPolicy() {
  useSeo({
    title: "Privacy Policy | Luxmorai Technologies",
    description: "Learn how Luxmorai Technologies collects, uses, stores, shares, and protects personal information.",
    path: "/privacy-policy",
  });

  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      updated="18 July 2026"
      intro="This policy explains how Luxmorai Technologies Pvt Ltd handles personal data when you use our website, contact us, apply for a role, or participate in our recruitment process."
    >
      <section>
        <h2>1. Who we are</h2>
        <p>
          Luxmorai Technologies Pvt Ltd ("Luxmorai", "we", "us" or "our") provides software, AI, cloud,
          website, mobile application, CRM, automation, design, testing, analytics, digital marketing and
          related technology services. For personal data handled through this website, Luxmorai is the
          organisation responsible for deciding why and how that data is processed.
        </p>
      </section>

      <section>
        <h2>2. Personal data we collect</h2>
        <p>Depending on how you interact with us, we may collect:</p>
        <ul>
          <li><strong>Contact inquiries:</strong> name, email address, phone number, requested service and message.</li>
          <li><strong>Job applications:</strong> name, email, phone number, current and permanent address, PIN codes, role, work experience, current and expected compensation, career-gap details, message and resume.</li>
          <li><strong>Recruitment records:</strong> application number, status, status communications, internal recruitment notes and information provided during screening or interviews.</li>
          <li><strong>Assessment information:</strong> name, email, answers and score used in the browser. The current assessment page checks camera and microphone permission, immediately stops the media stream, and does not record or upload audio or video.</li>
          <li><strong>Technical information:</strong> IP address, browser or device information, request times, errors and security logs generated by hosting and infrastructure providers.</li>
          <li><strong>Communications:</strong> emails, calls and other correspondence with our business or recruitment teams.</li>
        </ul>
        <p>Please do not send government identification numbers, financial credentials, medical information or other unnecessary sensitive information through open website forms.</p>
      </section>

      <section>
        <h2>3. How we collect data</h2>
        <p>
          We collect data directly from you through website forms, job applications, resumes, emails, calls
          and recruitment interactions. Limited technical data may be collected automatically by the website,
          server, database, security and hosting systems used to operate the service.
        </p>
      </section>

      <section>
        <h2>4. Why we use personal data</h2>
        <ul>
          <li>To answer inquiries, understand requirements and prepare proposals.</li>
          <li>To provide, secure, maintain and improve our website and services.</li>
          <li>To receive applications, verify applicant details, assess suitability, communicate status and manage recruitment.</li>
          <li>To prevent fraud, misuse, security incidents and unauthorised access.</li>
          <li>To maintain business, accounting, compliance and dispute-resolution records.</li>
          <li>To comply with applicable law and respond to valid legal requests.</li>
        </ul>
        <p>
          We process personal data with your consent where consent is required, to take steps at your request,
          for legitimate uses permitted by law, and to meet legal obligations. You may withdraw consent by
          contacting us, but this will not affect processing already lawfully completed.
        </p>
      </section>

      <section>
        <h2>5. Recruitment information</h2>
        <p>
          Recruitment information is used only for hiring, candidate communication, verification, assessment,
          interview planning, workforce planning, legal compliance and related record keeping. Submitting an
          application does not guarantee an interview, selection or employment offer. We may verify information
          supplied by a candidate where lawful and appropriate.
        </p>
      </section>

      <section>
        <h2>6. When we share data</h2>
        <p>We do not sell personal data. We may share only what is reasonably necessary with:</p>
        <ul>
          <li>Authorised Luxmorai personnel involved in operations, support, security or recruitment.</li>
          <li>Hosting, cloud, database, storage, email delivery and technology providers operating under appropriate obligations.</li>
          <li>Professional advisers, auditors, insurers or transaction advisers where confidentiality protections apply.</li>
          <li>Government, regulatory, judicial or law-enforcement authorities when disclosure is legally required.</li>
          <li>A successor organisation in a lawful merger, restructuring or transfer, subject to appropriate safeguards.</li>
        </ul>
      </section>

      <section>
        <h2>7. International processing</h2>
        <p>
          Some infrastructure or service providers may process information outside your state or outside India.
          Where this occurs, we take reasonable steps to use contractual, organisational and technical safeguards
          and follow restrictions imposed by applicable law.
        </p>
      </section>

      <section>
        <h2>8. Cookies and local storage</h2>
        <p>
          The public website does not currently use advertising or behavioural-tracking cookies. Essential browser
          storage or session technologies may be used for security and administrative sign-in functionality.
          Infrastructure providers may also use necessary cookies or logs to deliver and protect the service. If we
          introduce non-essential analytics or advertising technologies, we will update this policy and provide any
          consent controls required by law.
        </p>
      </section>

      <section>
        <h2>9. Retention</h2>
        <p>
          We retain personal data only for as long as reasonably necessary for the purpose described in this policy,
          recruitment and business record keeping, security, legal compliance, or legal claims. Retention needs are
          reviewed periodically. When data is no longer required, we take reasonable steps to delete, anonymise or
          securely isolate it, subject to backup cycles and legal obligations.
        </p>
      </section>

      <section>
        <h2>10. Security</h2>
        <p>
          We use reasonable administrative, technical and organisational safeguards intended to protect personal data,
          including access restrictions, managed infrastructure and secure transmission where supported. No internet
          transmission or storage system is completely secure, so we cannot promise absolute security. Please contact
          us promptly if you believe your information or application number has been compromised.
        </p>
      </section>

      <section>
        <h2>11. Your choices and rights</h2>
        <p>Subject to applicable law, you may ask us to:</p>
        <ul>
          <li>Confirm whether we process your personal data and provide available information about that processing.</li>
          <li>Correct, complete or update inaccurate personal data.</li>
          <li>Delete personal data that is no longer required or must be erased by law.</li>
          <li>Withdraw consent or object to particular communications.</li>
          <li>Raise a grievance and receive information about available complaint channels.</li>
          <li>Nominate another person to exercise applicable rights in circumstances recognised by law.</li>
        </ul>
        <p>
          We may need to verify your identity before acting. Some information may be retained where required by law or
          needed for security, fraud prevention, contracts or legal claims.
        </p>
      </section>

      <section>
        <h2>12. Children</h2>
        <p>
          Our business website and recruitment services are not directed to children. We do not knowingly seek personal
          data from anyone under 18 through career forms. If you believe a child has provided personal data without
          appropriate authorisation, contact us so that we can review and address it.
        </p>
      </section>

      <section>
        <h2>13. External links</h2>
        <p>
          The website may link to third-party services such as LinkedIn. Their privacy practices are controlled by their
          own policies, and this policy does not govern information you provide directly to those third parties.
        </p>
      </section>

      <section>
        <h2>14. Changes to this policy</h2>
        <p>
          We may update this policy when our services, technology or legal obligations change. The revised version will
          be posted here with a new “Last updated” date. Material changes may also be communicated through an appropriate
          additional notice.
        </p>
      </section>

      <section>
        <h2>15. Privacy and grievance contact</h2>
        <p>
          Data Protection and Grievance Team<br />
          Luxmorai Technologies Pvt Ltd<br />
          19/3RT, Line 2, Street 5, Prakash Nagar, Begumpet, Hyderabad, Telangana 500016, India<br />
          Email: <a href="mailto:info@luxmorai.com">info@luxmorai.com</a><br />
          Recruitment privacy requests: <a href="mailto:hr@luxmorai.com">hr@luxmorai.com</a><br />
          Phone: <a href="tel:+919884050511">+91 9884050511</a>
        </p>
        <p>Please describe your request clearly and include enough information for us to identify the relevant record.</p>
      </section>

      <p className="legal-related-link">Also read our <Link to="/terms-and-conditions">Terms and Conditions</Link>.</p>
    </LegalPage>
  );
}
